[2023-12-05 12:27:49,437: INFO: main: welcom to our custom log]
[2023-12-05 13:51:52,488: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 13:52:32,991: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 13:52:34,735: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 13:52:46,353: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 13:52:46,364: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 13:53:09,282: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 13:53:09,284: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 14:04:14,798: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 14:04:14,801: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 14:05:35,314: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 14:05:35,317: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 14:05:35,319: INFO: common: created directory at: artifacts]
[2023-12-05 14:05:35,319: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-05 14:05:35,325: INFO: 2204213689: Downloading data from https://drive.google.com/file/d/1k60akcZt52JZO4ULY_ZOKeIXZ0QvYbav/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-05 14:05:56,868: INFO: 2204213689: Downloaded data from https://drive.google.com/file/d/1k60akcZt52JZO4ULY_ZOKeIXZ0QvYbav/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-05 14:24:22,232: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-05 14:24:22,234: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 14:24:22,236: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 14:24:22,237: INFO: common: created directory at: artifacts]
[2023-12-05 14:24:22,238: ERROR: main: 'ConfigurationManager' object has no attribute 'get_data_ingestion_config']
Traceback (most recent call last):
  File "d:\Kidney-Disease-classification-Deep-learning-project\main.py", line 12, in <module>
    data_ingestion.main()
  File "d:\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 14, in main
    data_ingestion_config = config.get_data_ingestion_config()
AttributeError: 'ConfigurationManager' object has no attribute 'get_data_ingestion_config'
[2023-12-05 14:29:50,262: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-05 14:29:50,262: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 14:29:50,262: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 14:29:50,271: INFO: common: created directory at: artifacts]
[2023-12-05 14:29:50,272: ERROR: main: 'ConfigurationManager' object has no attribute 'get_data_ingestion_config']
Traceback (most recent call last):
  File "D:\Kidney-Disease-classification-Deep-learning-project\main.py", line 12, in <module>
    data_ingestion.main()
  File "d:\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 14, in main
    data_ingestion_config = config.get_data_ingestion_config()
AttributeError: 'ConfigurationManager' object has no attribute 'get_data_ingestion_config'
[2023-12-05 14:40:23,082: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-05 14:40:23,086: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 14:40:23,103: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 14:40:23,104: INFO: common: created directory at: artifacts]
[2023-12-05 14:40:23,104: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-05 14:40:23,104: INFO: data_ingesation: Downloading data from https://drive.google.com/file/d/1k60akcZt52JZO4ULY_ZOKeIXZ0QvYbav/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-05 14:40:34,999: INFO: data_ingesation: Downloaded data from https://drive.google.com/file/d/1k60akcZt52JZO4ULY_ZOKeIXZ0QvYbav/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-05 14:40:36,469: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-05 15:05:31,095: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 15:05:31,098: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 15:05:31,099: INFO: common: created directory at: artifacts]
[2023-12-05 15:05:31,101: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-05 15:08:18,768: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 15:08:18,776: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 15:08:18,778: INFO: common: created directory at: artifacts]
[2023-12-05 15:08:18,779: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-05 15:08:19,253: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-05 15:20:58,542: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-05 15:20:58,544: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 15:20:58,546: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 15:20:58,547: INFO: common: created directory at: artifacts]
[2023-12-05 15:20:58,547: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-05 15:20:58,548: INFO: data_ingesation: Downloading data from https://drive.google.com/file/d/1k60akcZt52JZO4ULY_ZOKeIXZ0QvYbav/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-05 15:22:09,171: INFO: data_ingesation: Downloaded data from https://drive.google.com/file/d/1k60akcZt52JZO4ULY_ZOKeIXZ0QvYbav/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-05 15:22:11,300: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-05 15:22:11,301: INFO: main: *******************]
[2023-12-05 15:22:11,301: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-12-05 15:22:11,301: ERROR: main: name 'PrepareBaseModelTrainingPipeline' is not defined]
Traceback (most recent call last):
  File "D:\Kidney-Disease-classification-Deep-learning-project\main.py", line 24, in <module>
    prepare_base_model = PrepareBaseModelTrainingPipeline()
NameError: name 'PrepareBaseModelTrainingPipeline' is not defined
[2023-12-05 15:28:19,589: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-05 15:28:19,602: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 15:28:19,605: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 15:28:19,605: INFO: common: created directory at: artifacts]
[2023-12-05 15:28:19,605: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-05 15:28:19,605: INFO: data_ingesation: Downloading data from https://drive.google.com/file/d/1k60akcZt52JZO4ULY_ZOKeIXZ0QvYbav/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-05 15:28:39,250: INFO: data_ingesation: Downloaded data from https://drive.google.com/file/d/1k60akcZt52JZO4ULY_ZOKeIXZ0QvYbav/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-05 15:28:41,503: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-05 15:28:41,503: INFO: main: *******************]
[2023-12-05 15:28:41,503: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-12-05 15:28:41,503: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 15:28:41,503: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 15:28:41,503: INFO: common: created directory at: artifacts]
[2023-12-05 15:28:41,512: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-05 15:28:41,836: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-05 15:28:42,024: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-12-05 15:37:56,845: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-05 15:37:56,853: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 15:37:56,855: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 15:37:56,855: INFO: common: created directory at: artifacts]
[2023-12-05 15:37:56,855: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-05 15:37:56,855: INFO: data_ingesation: Downloading data from https://drive.google.com/file/d/1k60akcZt52JZO4ULY_ZOKeIXZ0QvYbav/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-05 15:38:11,874: INFO: data_ingesation: Downloaded data from https://drive.google.com/file/d/1k60akcZt52JZO4ULY_ZOKeIXZ0QvYbav/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-05 15:38:13,366: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-05 15:38:13,366: INFO: main: *******************]
[2023-12-05 15:38:13,366: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-12-05 15:38:13,372: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 15:38:13,376: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 15:38:13,377: INFO: common: created directory at: artifacts]
[2023-12-05 15:38:13,378: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-05 15:38:13,715: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-05 15:38:13,908: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-12-05 15:38:13,909: INFO: main: *******************]
[2023-12-05 15:38:13,910: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-12-05 15:38:13,912: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 15:38:13,914: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 15:38:13,915: INFO: common: created directory at: artifacts]
[2023-12-05 15:38:13,916: INFO: common: created directory at: artifacts\training]
[2023-12-05 15:39:13,312: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-12-05 16:24:04,978: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 16:24:04,983: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 16:24:04,987: INFO: common: created directory at: artifacts]
[2023-12-05 16:24:33,041: INFO: common: json file saved at: scores.json]
[2023-12-05 16:24:39,223: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2023-12-05 16:24:39,688: INFO: builder_impl: Assets written to: C:\Users\KETAN~1.SAL\AppData\Local\Temp\tmp_5hb5k8j\model\data\model\assets]
[2023-12-05 16:34:20,691: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 16:34:20,707: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 16:34:20,710: INFO: common: created directory at: artifacts]
[2023-12-05 16:34:39,620: INFO: common: json file saved at: scores.json]
[2023-12-05 16:34:43,137: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2023-12-05 16:34:43,536: INFO: builder_impl: Assets written to: C:\Users\KETAN~1.SAL\AppData\Local\Temp\tmpd1o3mw7l\model\data\model\assets]
[2023-12-05 16:47:45,538: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-05 16:47:45,540: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 16:47:45,542: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 16:47:45,543: INFO: common: created directory at: artifacts]
[2023-12-05 16:47:45,543: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-05 16:47:45,543: INFO: data_ingesation: Downloading data from https://drive.google.com/file/d/1k60akcZt52JZO4ULY_ZOKeIXZ0QvYbav/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-05 16:47:59,101: INFO: data_ingesation: Downloaded data from https://drive.google.com/file/d/1k60akcZt52JZO4ULY_ZOKeIXZ0QvYbav/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-05 16:48:00,798: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-05 16:48:00,799: INFO: main: *******************]
[2023-12-05 16:48:00,799: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-12-05 16:48:00,801: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 16:48:00,804: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 16:48:00,806: INFO: common: created directory at: artifacts]
[2023-12-05 16:48:00,808: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-05 16:48:01,189: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-05 16:48:01,392: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-12-05 16:48:01,393: INFO: main: *******************]
[2023-12-05 16:48:01,393: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-12-05 16:48:01,395: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 16:48:01,398: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 16:48:01,399: INFO: common: created directory at: artifacts]
[2023-12-05 16:48:01,400: INFO: common: created directory at: artifacts\training]
[2023-12-05 16:49:13,754: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-12-05 16:49:13,755: INFO: main: *******************]
[2023-12-05 16:49:13,755: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2023-12-05 16:49:13,756: ERROR: main: name 'EvaluationPipeline' is not defined]
Traceback (most recent call last):
  File "D:\Kidney-Disease-classification-Deep-learning-project\main.py", line 51, in <module>
    model_evalution = EvaluationPipeline()
NameError: name 'EvaluationPipeline' is not defined
[2023-12-05 16:53:43,632: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-05 16:53:43,640: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 16:53:43,640: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 16:53:43,644: INFO: common: created directory at: artifacts]
[2023-12-05 16:53:43,644: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-05 16:53:43,644: INFO: data_ingesation: Downloading data from https://drive.google.com/file/d/1k60akcZt52JZO4ULY_ZOKeIXZ0QvYbav/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-05 16:54:05,382: INFO: data_ingesation: Downloaded data from https://drive.google.com/file/d/1k60akcZt52JZO4ULY_ZOKeIXZ0QvYbav/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-05 16:54:07,460: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-05 16:54:07,460: INFO: main: *******************]
[2023-12-05 16:54:07,460: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-12-05 16:54:07,460: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 16:54:07,476: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 16:54:07,477: INFO: common: created directory at: artifacts]
[2023-12-05 16:54:07,478: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-05 16:54:07,806: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-05 16:54:08,077: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-12-05 16:54:08,078: INFO: main: *******************]
[2023-12-05 16:54:08,078: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-12-05 16:54:08,080: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 16:54:08,083: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 16:54:08,083: INFO: common: created directory at: artifacts]
[2023-12-05 16:54:08,084: INFO: common: created directory at: artifacts\training]
[2023-12-05 16:55:03,175: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-12-05 16:55:03,176: INFO: main: *******************]
[2023-12-05 16:55:03,176: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2023-12-05 16:55:03,176: ERROR: main: name 'EvaluationPipeline' is not defined]
Traceback (most recent call last):
  File "D:\Kidney-Disease-classification-Deep-learning-project\main.py", line 51, in <module>
    model_evalution = EvaluationPipeline()
NameError: name 'EvaluationPipeline' is not defined
[2023-12-05 16:56:07,707: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-05 16:56:07,709: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 16:56:07,711: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 16:56:07,713: INFO: common: created directory at: artifacts]
[2023-12-05 16:56:07,713: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-05 16:56:07,714: INFO: data_ingesation: Downloading data from https://drive.google.com/file/d/1k60akcZt52JZO4ULY_ZOKeIXZ0QvYbav/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-05 16:56:10,576: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts/data_ingestion']
Traceback (most recent call last):
  File "D:\Kidney-Disease-classification-Deep-learning-project\main.py", line 12, in <module>
    data_ingestion.main()
  File "d:\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "d:\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\data_ingesation.py", line 33, in download_file
    raise e
  File "d:\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\data_ingesation.py", line 28, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\gdown\download.py", line 275, in download
    for file in os.listdir(osp.dirname(output) or "."):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts/data_ingestion'
[2023-12-05 16:56:27,577: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-05 16:56:27,582: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 16:56:27,582: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 16:56:27,588: INFO: common: created directory at: artifacts]
[2023-12-05 16:56:27,589: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-05 16:56:27,589: INFO: data_ingesation: Downloading data from https://drive.google.com/file/d/1k60akcZt52JZO4ULY_ZOKeIXZ0QvYbav/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-05 16:56:40,174: INFO: data_ingesation: Downloaded data from https://drive.google.com/file/d/1k60akcZt52JZO4ULY_ZOKeIXZ0QvYbav/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-05 16:56:41,710: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-05 16:56:41,711: INFO: main: *******************]
[2023-12-05 16:56:41,711: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-12-05 16:56:41,715: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 16:56:41,717: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 16:56:41,718: INFO: common: created directory at: artifacts]
[2023-12-05 16:56:41,719: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-05 16:56:42,047: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-05 16:56:42,214: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-12-05 16:56:42,214: INFO: main: *******************]
[2023-12-05 16:56:42,214: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-12-05 16:56:42,214: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 16:56:42,229: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 16:56:42,230: INFO: common: created directory at: artifacts]
[2023-12-05 16:56:42,231: INFO: common: created directory at: artifacts\training]
[2023-12-05 16:57:44,465: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-12-05 16:57:44,466: INFO: main: *******************]
[2023-12-05 16:57:44,466: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2023-12-05 16:57:44,471: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 16:57:44,474: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 16:57:44,475: INFO: common: created directory at: artifacts]
[2023-12-05 16:58:03,039: INFO: common: json file saved at: scores.json]
[2023-12-05 16:58:03,052: INFO: common: json file saved at: scores.json]
[2023-12-05 16:58:03,052: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-12-05 17:03:08,459: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-05 17:03:08,464: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 17:03:08,466: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 17:03:08,467: INFO: common: created directory at: artifacts]
[2023-12-05 17:03:08,468: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-05 17:03:08,469: INFO: data_ingesation: Downloading data from https://drive.google.com/file/d/1k60akcZt52JZO4ULY_ZOKeIXZ0QvYbav/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-05 17:03:38,482: INFO: data_ingesation: Downloaded data from https://drive.google.com/file/d/1k60akcZt52JZO4ULY_ZOKeIXZ0QvYbav/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-05 17:03:40,525: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-05 17:03:40,526: INFO: main: *******************]
[2023-12-05 17:03:40,526: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-12-05 17:03:40,530: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 17:03:40,533: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 17:03:40,535: INFO: common: created directory at: artifacts]
[2023-12-05 17:03:40,536: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-05 17:03:40,865: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-05 17:03:41,147: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-12-05 17:03:41,147: INFO: main: *******************]
[2023-12-05 17:03:41,147: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-12-05 17:03:41,150: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 17:03:41,153: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 17:03:41,154: INFO: common: created directory at: artifacts]
[2023-12-05 17:03:41,155: INFO: common: created directory at: artifacts\training]
[2023-12-05 17:04:33,497: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-12-05 17:04:33,498: INFO: main: *******************]
[2023-12-05 17:04:33,499: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2023-12-05 17:04:33,503: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 17:04:33,506: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 17:04:33,507: INFO: common: created directory at: artifacts]
[2023-12-05 17:04:52,259: INFO: common: json file saved at: scores.json]
[2023-12-05 17:04:52,265: INFO: common: json file saved at: scores.json]
[2023-12-05 17:04:52,266: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-12-05 17:17:27,422: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-05 17:17:27,425: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 17:17:27,426: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 17:17:27,427: INFO: common: created directory at: artifacts]
[2023-12-05 17:17:27,428: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-05 17:17:27,428: INFO: data_ingesation: Downloading data from https://drive.google.com/file/d/1k60akcZt52JZO4ULY_ZOKeIXZ0QvYbav/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-05 17:17:40,958: INFO: data_ingesation: Downloaded data from https://drive.google.com/file/d/1k60akcZt52JZO4ULY_ZOKeIXZ0QvYbav/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-05 17:17:42,594: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-05 17:19:10,542: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-05 17:19:10,542: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 17:19:10,561: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 17:19:10,564: INFO: common: created directory at: artifacts]
[2023-12-05 17:19:10,565: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-05 17:19:10,566: INFO: data_ingesation: Downloading data from https://drive.google.com/file/d/1k60akcZt52JZO4ULY_ZOKeIXZ0QvYbav/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-05 17:19:25,721: INFO: data_ingesation: Downloaded data from https://drive.google.com/file/d/1k60akcZt52JZO4ULY_ZOKeIXZ0QvYbav/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-05 17:19:27,304: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-05 17:31:57,504: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-05 17:31:57,506: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 17:31:57,506: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 17:31:57,506: INFO: common: created directory at: artifacts]
[2023-12-05 17:31:57,506: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-05 17:31:57,506: INFO: data_ingesation: Downloading data from https://drive.google.com/file/d/1k60akcZt52JZO4ULY_ZOKeIXZ0QvYbav/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-05 17:35:29,518: INFO: data_ingesation: Downloaded data from https://drive.google.com/file/d/1k60akcZt52JZO4ULY_ZOKeIXZ0QvYbav/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-05 17:35:31,115: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-05 17:35:31,115: INFO: main: *******************]
[2023-12-05 17:35:31,115: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-12-05 17:35:31,115: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 17:35:31,123: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 17:35:31,125: INFO: common: created directory at: artifacts]
[2023-12-05 17:35:31,125: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-05 17:35:31,496: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-05 17:35:31,674: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-12-05 17:35:31,675: INFO: main: *******************]
[2023-12-05 17:35:31,675: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-12-05 17:35:31,675: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 17:35:31,675: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 17:35:31,675: INFO: common: created directory at: artifacts]
[2023-12-05 17:35:31,675: INFO: common: created directory at: artifacts\training]
[2023-12-05 17:35:34,892: ERROR: main: Graph execution error:

Detected at node 'categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):
    File "D:\Kidney-Disease-classification-Deep-learning-project\main.py", line 39, in <module>
      model_trainer.main()
    File "d:\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
      training.train()
    File "d:\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 76, in train
      self.model.fit(
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1051, in train_step
      loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1109, in compute_loss
      return self.compiled_loss(
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\engine\compile_utils.py", line 265, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\losses.py", line 142, in __call__
      losses = call_fn(y_true, y_pred)
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\losses.py", line 268, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\losses.py", line 1984, in categorical_crossentropy
      return backend.categorical_crossentropy(
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\backend.py", line 5565, in categorical_crossentropy
      return tf.nn.softmax_cross_entropy_with_logits(
Node: 'categorical_crossentropy/softmax_cross_entropy_with_logits'
logits and labels must be broadcastable: logits_size=[16,3] labels_size=[16,2]
	 [[{{node categorical_crossentropy/softmax_cross_entropy_with_logits}}]] [Op:__inference_train_function_1463]]
Traceback (most recent call last):
  File "D:\Kidney-Disease-classification-Deep-learning-project\main.py", line 39, in <module>
    model_trainer.main()
  File "d:\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
    training.train()
  File "d:\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 76, in train
    self.model.fit(
  File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\tensorflow\python\eager\execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node 'categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):
    File "D:\Kidney-Disease-classification-Deep-learning-project\main.py", line 39, in <module>
      model_trainer.main()
    File "d:\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
      training.train()
    File "d:\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 76, in train
      self.model.fit(
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1051, in train_step
      loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1109, in compute_loss
      return self.compiled_loss(
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\engine\compile_utils.py", line 265, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\losses.py", line 142, in __call__
      losses = call_fn(y_true, y_pred)
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\losses.py", line 268, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\losses.py", line 1984, in categorical_crossentropy
      return backend.categorical_crossentropy(
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\backend.py", line 5565, in categorical_crossentropy
      return tf.nn.softmax_cross_entropy_with_logits(
Node: 'categorical_crossentropy/softmax_cross_entropy_with_logits'
logits and labels must be broadcastable: logits_size=[16,3] labels_size=[16,2]
	 [[{{node categorical_crossentropy/softmax_cross_entropy_with_logits}}]] [Op:__inference_train_function_1463]
[2023-12-05 17:38:18,739: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-05 17:38:18,743: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 17:38:18,745: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 17:38:18,746: INFO: common: created directory at: artifacts]
[2023-12-05 17:38:18,746: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-05 17:38:18,746: INFO: data_ingesation: Downloading data from https://drive.google.com/file/d/1k60akcZt52JZO4ULY_ZOKeIXZ0QvYbav/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-05 17:38:35,977: INFO: data_ingesation: Downloaded data from https://drive.google.com/file/d/1k60akcZt52JZO4ULY_ZOKeIXZ0QvYbav/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-05 17:38:37,472: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-05 17:38:37,473: INFO: main: *******************]
[2023-12-05 17:38:37,473: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-12-05 17:38:37,476: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 17:38:37,479: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 17:38:37,481: INFO: common: created directory at: artifacts]
[2023-12-05 17:38:37,483: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-05 17:38:37,818: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-05 17:38:38,076: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-12-05 17:38:38,077: INFO: main: *******************]
[2023-12-05 17:38:38,077: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-12-05 17:38:38,080: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 17:38:38,082: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 17:38:38,082: INFO: common: created directory at: artifacts]
[2023-12-05 17:38:38,083: INFO: common: created directory at: artifacts\training]
[2023-12-05 17:38:40,875: ERROR: main: Graph execution error:

Detected at node 'categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):
    File "D:\Kidney-Disease-classification-Deep-learning-project\main.py", line 39, in <module>
      model_trainer.main()
    File "d:\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
      training.train()
    File "d:\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 76, in train
      self.model.fit(
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1051, in train_step
      loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1109, in compute_loss
      return self.compiled_loss(
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\engine\compile_utils.py", line 265, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\losses.py", line 142, in __call__
      losses = call_fn(y_true, y_pred)
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\losses.py", line 268, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\losses.py", line 1984, in categorical_crossentropy
      return backend.categorical_crossentropy(
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\backend.py", line 5565, in categorical_crossentropy
      return tf.nn.softmax_cross_entropy_with_logits(
Node: 'categorical_crossentropy/softmax_cross_entropy_with_logits'
logits and labels must be broadcastable: logits_size=[16,3] labels_size=[16,2]
	 [[{{node categorical_crossentropy/softmax_cross_entropy_with_logits}}]] [Op:__inference_train_function_1463]]
Traceback (most recent call last):
  File "D:\Kidney-Disease-classification-Deep-learning-project\main.py", line 39, in <module>
    model_trainer.main()
  File "d:\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
    training.train()
  File "d:\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 76, in train
    self.model.fit(
  File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\tensorflow\python\eager\execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node 'categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):
    File "D:\Kidney-Disease-classification-Deep-learning-project\main.py", line 39, in <module>
      model_trainer.main()
    File "d:\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
      training.train()
    File "d:\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 76, in train
      self.model.fit(
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1051, in train_step
      loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1109, in compute_loss
      return self.compiled_loss(
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\engine\compile_utils.py", line 265, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\losses.py", line 142, in __call__
      losses = call_fn(y_true, y_pred)
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\losses.py", line 268, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\losses.py", line 1984, in categorical_crossentropy
      return backend.categorical_crossentropy(
    File "C:\Users\Ketan.Salian\AppData\Local\anaconda3\envs\kidney\lib\site-packages\keras\backend.py", line 5565, in categorical_crossentropy
      return tf.nn.softmax_cross_entropy_with_logits(
Node: 'categorical_crossentropy/softmax_cross_entropy_with_logits'
logits and labels must be broadcastable: logits_size=[16,3] labels_size=[16,2]
	 [[{{node categorical_crossentropy/softmax_cross_entropy_with_logits}}]] [Op:__inference_train_function_1463]
[2023-12-05 17:40:51,640: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-05 17:40:51,646: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 17:40:51,650: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 17:40:51,652: INFO: common: created directory at: artifacts]
[2023-12-05 17:40:51,652: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-05 17:40:51,653: INFO: data_ingesation: Downloading data from https://drive.google.com/file/d/1k60akcZt52JZO4ULY_ZOKeIXZ0QvYbav/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-05 17:41:05,513: INFO: data_ingesation: Downloaded data from https://drive.google.com/file/d/1k60akcZt52JZO4ULY_ZOKeIXZ0QvYbav/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-05 17:41:07,100: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-05 17:41:07,101: INFO: main: *******************]
[2023-12-05 17:41:07,102: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-12-05 17:41:07,107: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 17:41:07,110: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 17:41:07,111: INFO: common: created directory at: artifacts]
[2023-12-05 17:41:07,112: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-05 17:41:07,452: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-05 17:41:07,711: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-12-05 17:41:07,711: INFO: main: *******************]
[2023-12-05 17:41:07,711: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-12-05 17:41:07,714: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 17:41:07,717: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 17:41:07,718: INFO: common: created directory at: artifacts]
[2023-12-05 17:41:07,719: INFO: common: created directory at: artifacts\training]
[2023-12-05 17:42:03,030: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-12-05 17:42:03,030: INFO: main: *******************]
[2023-12-05 17:42:03,030: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2023-12-05 17:42:03,030: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 17:42:03,049: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 17:42:03,051: INFO: common: created directory at: artifacts]
[2023-12-05 17:42:21,889: INFO: common: json file saved at: scores.json]
[2023-12-05 17:42:21,898: INFO: common: json file saved at: scores.json]
[2023-12-05 17:42:21,899: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-12-05 17:43:32,908: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-05 17:43:32,911: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 17:43:32,916: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 17:43:32,917: INFO: common: created directory at: artifacts]
[2023-12-05 17:43:32,921: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-05 17:43:32,921: INFO: data_ingesation: Downloading data from https://drive.google.com/file/d/1k60akcZt52JZO4ULY_ZOKeIXZ0QvYbav/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-05 17:43:44,459: INFO: data_ingesation: Downloaded data from https://drive.google.com/file/d/1k60akcZt52JZO4ULY_ZOKeIXZ0QvYbav/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-05 17:43:46,013: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-05 17:44:02,183: INFO: stage_02_prepare_base_model: *******************]
[2023-12-05 17:44:02,184: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2023-12-05 17:44:02,187: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 17:44:02,190: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 17:44:02,190: INFO: common: created directory at: artifacts]
[2023-12-05 17:44:02,191: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-05 17:44:02,544: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-05 17:44:02,726: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-12-05 17:44:12,216: INFO: stage_03_model_training: *******************]
[2023-12-05 17:44:12,217: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2023-12-05 17:44:12,220: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 17:44:12,222: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 17:44:12,223: INFO: common: created directory at: artifacts]
[2023-12-05 17:44:12,224: INFO: common: created directory at: artifacts\training]
[2023-12-05 17:45:16,758: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-12-05 17:45:29,030: INFO: stage_04_model_evaluation: *******************]
[2023-12-05 17:45:29,038: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2023-12-05 17:45:29,039: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-05 17:45:29,039: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-05 17:45:29,039: INFO: common: created directory at: artifacts]
[2023-12-05 17:45:55,204: INFO: common: json file saved at: scores.json]
[2023-12-05 17:45:55,207: INFO: common: json file saved at: scores.json]
[2023-12-05 17:45:55,208: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
